apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: quay.io
      containers:
        - name: my-app
          image: {{ .Values.image.repository }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
#          volumeMounts:
 #           - name: registry-cert
  #            mountPath: "/etc/pki/ca-trust/source/anchors"
   #           readOnly: true
    #  volumes:
     #   - name: registry-cert
      #    secret:
       #    secretName: registry-cert-secret
