apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: dockersecret-1
      containers:
        - name: my-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
##          volumeMounts:
####            - name: registry-cert
##              mountPath: "/etc/registry-certs"
#              readOnly: true
 #     volumes:
#        - name: registry-cert
  #        secret:
 #          secretName: registry-cert-secret
